In [1]:
from ising_model import ClassicIsing, TransverseIsing
import electron
from grid import Grid, HoleGrid, Mobius, Cylinder, Torus
import numpy as np
from equilibrator import equilibrate_grid, proper_equilibration

# Before running the code, make sure to reset the kernel to clear any old imports.

In [9]:
newGrid = Grid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(newGrid, temperature=1, ferromagnetivity=1,Mf_External=0)


#isingModel.runSimulation(10)

# equilibrate the grid keeping track of grid history.
print(isingModel.magnetization())
equilibrate_grid(newGrid, equil_tolerance=0.9, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(newGrid.output(grid=isingModel.grid.grid_history[0]))
print(newGrid.output(grid=isingModel.grid.grid_history[-1]))

0.2
0.88
[[ 1. -1.  1.  1.  1. -1.  1. -1. -1. -1.]
 [-1.  1.  1.  1.  1.  1.  1. -1.  1. -1.]
 [-1.  1.  1.  1.  1.  1. -1. -1.  1. -1.]
 [ 1. -1. -1. -1.  1. -1.  1.  1.  1. -1.]
 [ 1.  1. -1.  1.  1.  1. -1. -1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1. -1.  1. -1.  1.]
 [ 1.  1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1. -1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1. -1. -1.  1.  1.  1.  1. -1.]
 [-1.  1.  1.  1. -1.  1. -1. -1. -1.  1.]]
[[ 1. -1. -1.  1. -1. -1. -1. -1. -1. -1.]
 [ 1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]]


In [12]:
holeGrid = HoleGrid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, hole_grid=np.ones((3,3)) ,c_y=2, c_x=2)
isingModel = ClassicIsing(holeGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

#isingModel.runSimulation(10)

# equilibrate the grid keeping track of grid history
print(isingModel.magnetization())
equilibrate_grid(holeGrid, equil_tolerance=0.8, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(holeGrid.output(grid=isingModel.grid.grid_history[1]))
print(holeGrid.output(grid=isingModel.grid.grid_history[-1]))


0.09
0.83
[[ 1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [-1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0. -1. -1.  1. -1. -1.  1.]
 [-1.  1. -1. -1. -1. -1. -1. -1. -1.  1.]
 [ 1.  1.  1. -1.  1. -1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1.  1.  1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1.  1.  1.  1.  1.  1. -1. -1.]]
[[ 1.  1.  1. -1. -1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [13]:
mobiusGrid = Mobius(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(mobiusGrid, temperature=1, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(mobiusGrid, equil_tolerance=0.9, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(mobiusGrid.output(grid=isingModel.grid.grid_history[1]))
print(mobiusGrid.output(grid=isingModel.grid.grid_history[-1]))

0.06
0.96
[[-1. -1. -1.  1.  1.  1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  1.]
 [-1.  1. -1. -1. -1. -1. -1. -1. -1.  1.]
 [-1. -1. -1. -1.  1.  1. -1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.  1. -1. -1. -1. -1.]
 [ 1. -1. -1.  1.  1.  1.  1.  1. -1. -1.]
 [ 1. -1. -1. -1.  1.  1. -1. -1. -1. -1.]
 [ 1. -1. -1. -1.  1.  1. -1. -1. -1. -1.]
 [ 1. -1.  1. -1. -1. -1. -1. -1. -1. -1.]]
[[-1. -1. -1. -1. -1. -1.  1.  1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


In [16]:
cylinderGrid = Cylinder(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(cylinderGrid, temperature=1, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(cylinderGrid, equil_tolerance=0.9, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(cylinderGrid.output(grid=isingModel.grid.grid_history[1]))
print(cylinderGrid.output(grid=isingModel.grid.grid_history[-1]))

0.06
0.92
[[ 1.  1.  1.  1. -1. -1. -1.  1.  1.  1.]
 [ 1.  1. -1.  1. -1. -1. -1. -1.  1. -1.]
 [ 1.  1.  1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  1.  1. -1. -1. -1. -1. -1.  1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1. -1.  1.]
 [ 1. -1. -1. -1.  1. -1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. -1. -1.  1.  1.  1.]
 [-1. -1.  1.  1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  1.  1.  1.  1.  1. -1. -1. -1.]
 [ 1. -1. -1. -1.  1.  1.  1.  1. -1. -1.]]
[[-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1. -1. -1. -1. -1.]]


In [17]:
torusGrid = Torus(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(torusGrid, temperature=10, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(torusGrid, equil_tolerance=0.9, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(torusGrid.output(grid=isingModel.grid.grid_history[1]))
print(torusGrid.output(grid=isingModel.grid.grid_history[-1]))

0.1
0.98
[[ 1.  1.  1.  1. -1. -1. -1.  1.  1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1. -1.  1. -1.]
 [-1. -1. -1. -1. -1.  1.  1. -1. -1.  1.]
 [-1.  1.  1.  1.  1.  1.  1. -1. -1. -1.]
 [-1. -1.  1.  1.  1. -1. -1. -1. -1. -1.]
 [-1. -1.  1.  1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  1.  1.  1.  1.  1. -1. -1. -1.]
 [-1. -1.  1. -1.  1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. -1.  1.]
 [ 1.  1.  1.  1.  1.  1. -1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [7]:
tranverseIsing = TransverseIsing(n=2, coupling_strength=1, term_strength=1, rand_init=True)


print("Initial M:", tranverseIsing.magnetization())
tranverseIsing.runSimulation(n_steps=10, dt=0.1)

print(tranverseIsing.state_history[0])
print(tranverseIsing.state_history[-1])
print("Final M:", tranverseIsing.magnetization())



Initial M: -0.4036250627408261
[0.28769888+0.2120278j  0.19599481+0.15444144j 0.2867789 +0.44318598j
 0.69317896+0.22550926j]
[-0.26159608-0.24555279j -0.122758  -0.33762707j -0.37735049-0.36279499j
 -0.38557398-0.56526884j]
Final M: -0.33946747778553643
