In [7]:
from ising_model import ClassicIsing
import electron
from grid import Grid
import numpy as np

# Before runnign the code, make sure to reset the kernel to clear any old imports.

In [8]:
newGrid = Grid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, random_seed=2)
isingModel = ClassicIsing(newGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

isingModel.runSimulation(10)

print(isingModel.grid.grid_history[0].output())
print(isingModel.grid.grid_history[-1].output())

[[ 1.  1. -1. -1. -1. -1. -1.  1. -1.  1.]
 [-1. -1. -1. -1. -1. -1.  1. -1.  1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1. -1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1. -1.  1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1. -1.  1.  1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.  1.  1.  1.  1.  1.]]
[[ 1.  1. -1. -1. -1. -1. -1.  1. -1.  1.]
 [-1. -1. -1. -1. -1. -1.  1. -1.  1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1. -1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1. -1.  1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1. -1.  1.  1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1.  1.  1.  1.  1.]
 [-1.  1. -1.  1. -1.  1.  1.  1.  1.  1.]]
