In [13]:
from ising_model import ClassicIsing
import electron
from grid import Grid, HoleGrid
import numpy as np

# Before runnign the code, make sure to reset the kernel to clear any old imports.

In [14]:
newGrid = Grid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, random_seed=2)
isingModel = ClassicIsing(newGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

isingModel.runSimulation(10)

print(isingModel.grid.grid_history[0].output())
print(isingModel.grid.grid_history[-1].output())

[[ 1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
[[ 1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


In [20]:
holeGrid = HoleGrid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, random_seed=2, hole_grid=np.ones((3,3)) ,c_y=2, c_x=2)
isingModel = ClassicIsing(holeGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

isingModel.runSimulation(10)

print(isingModel.grid.grid_history[0].output())
print(isingModel.grid.grid_history[-1].output())

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [-1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1. -1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1.  1. -1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [-1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1. -1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1.  1. -1.  1.  1.]]
