In [8]:
from ising_model import ClassicIsing
import electron
from grid import Grid, HoleGrid, Mobius, Cylinder, Torus
import numpy as np
from equilibrator import equilibrate_grid, proper_equilibration

# Before running the code, make sure to reset the kernel to clear any old imports.

In [9]:
newGrid = Grid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(newGrid, temperature=1, ferromagnetivity=1,Mf_External=0)


#isingModel.runSimulation(10)

# equilibrate the grid keeping track of grid history.
print(isingModel.magnetization())
equilibrate_grid(newGrid, equil_tolerance=0.9, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(newGrid.output(grid=isingModel.grid.grid_history[0]))
print(newGrid.output(grid=isingModel.grid.grid_history[-1]))

0.2
0.88
[[ 1. -1.  1.  1.  1. -1.  1. -1. -1. -1.]
 [-1.  1.  1.  1.  1.  1.  1. -1.  1. -1.]
 [-1.  1.  1.  1.  1.  1. -1. -1.  1. -1.]
 [ 1. -1. -1. -1.  1. -1.  1.  1.  1. -1.]
 [ 1.  1. -1.  1.  1.  1. -1. -1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1. -1.  1. -1.  1.]
 [ 1.  1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1. -1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1. -1. -1.  1.  1.  1.  1. -1.]
 [-1.  1.  1.  1. -1.  1. -1. -1. -1.  1.]]
[[ 1. -1. -1.  1. -1. -1. -1. -1. -1. -1.]
 [ 1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]]


In [12]:
holeGrid = HoleGrid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, hole_grid=np.ones((3,3)) ,c_y=2, c_x=2)
isingModel = ClassicIsing(holeGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

#isingModel.runSimulation(10)

# equilibrate the grid keeping track of grid history
print(isingModel.magnetization())
equilibrate_grid(holeGrid, equil_tolerance=0.8, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(holeGrid.output(grid=isingModel.grid.grid_history[1]))
print(holeGrid.output(grid=isingModel.grid.grid_history[-1]))


0.09
0.83
[[ 1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [-1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0. -1. -1.  1. -1. -1.  1.]
 [-1.  1. -1. -1. -1. -1. -1. -1. -1.  1.]
 [ 1.  1.  1. -1.  1. -1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1.  1.  1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1.  1.  1.  1.  1.  1. -1. -1.]]
[[ 1.  1.  1. -1. -1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. -1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [13]:
mobiusGrid = Mobius(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(mobiusGrid, temperature=1, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(mobiusGrid, equil_tolerance=0.9, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(mobiusGrid.output(grid=isingModel.grid.grid_history[1]))
print(mobiusGrid.output(grid=isingModel.grid.grid_history[-1]))

0.06
0.96
[[-1. -1. -1.  1.  1.  1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  1.]
 [-1.  1. -1. -1. -1. -1. -1. -1. -1.  1.]
 [-1. -1. -1. -1.  1.  1. -1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.  1. -1. -1. -1. -1.]
 [ 1. -1. -1.  1.  1.  1.  1.  1. -1. -1.]
 [ 1. -1. -1. -1.  1.  1. -1. -1. -1. -1.]
 [ 1. -1. -1. -1.  1.  1. -1. -1. -1. -1.]
 [ 1. -1.  1. -1. -1. -1. -1. -1. -1. -1.]]
[[-1. -1. -1. -1. -1. -1.  1.  1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


In [16]:
cylinderGrid = Cylinder(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(cylinderGrid, temperature=1, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(cylinderGrid, equil_tolerance=0.9, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(cylinderGrid.output(grid=isingModel.grid.grid_history[1]))
print(cylinderGrid.output(grid=isingModel.grid.grid_history[-1]))

0.06
0.92
[[ 1.  1.  1.  1. -1. -1. -1.  1.  1.  1.]
 [ 1.  1. -1.  1. -1. -1. -1. -1.  1. -1.]
 [ 1.  1.  1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  1.  1. -1. -1. -1. -1. -1.  1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1. -1.  1.]
 [ 1. -1. -1. -1.  1. -1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. -1. -1.  1.  1.  1.]
 [-1. -1.  1.  1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  1.  1.  1.  1.  1. -1. -1. -1.]
 [ 1. -1. -1. -1.  1.  1.  1.  1. -1. -1.]]
[[-1. -1. -1. -1. -1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1. -1. -1. -1. -1.]]


In [17]:
torusGrid = Torus(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(torusGrid, temperature=10, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(torusGrid, equil_tolerance=0.9, J=isingModel.ferromagnetivity)
print(isingModel.magnetization())

print(torusGrid.output(grid=isingModel.grid.grid_history[1]))
print(torusGrid.output(grid=isingModel.grid.grid_history[-1]))

0.1
0.98
[[ 1.  1.  1.  1. -1. -1. -1.  1.  1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1. -1.  1. -1.]
 [-1. -1. -1. -1. -1.  1.  1. -1. -1.  1.]
 [-1.  1.  1.  1.  1.  1.  1. -1. -1. -1.]
 [-1. -1.  1.  1.  1. -1. -1. -1. -1. -1.]
 [-1. -1.  1.  1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  1.  1.  1.  1.  1. -1. -1. -1.]
 [-1. -1.  1. -1.  1.  1.  1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. -1.  1.]
 [ 1.  1.  1.  1.  1.  1. -1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
