In [1]:
from ising_model import ClassicIsing, TransverseIsing
import electron
from grid import Grid, HoleGrid, Mobius, Cylinder, Torus
import numpy as np
from equilibrator import equilibrate_grid, proper_equilibration

# Before running the code, make sure to reset the kernel to clear any old imports.

In [2]:
newGrid = Grid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(newGrid, temperature=1, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

# equilibrate the grid keeping track of grid history.
print(isingModel.magnetization())
equilibrate_grid(isingModel, equil_tolerance=0.9)
print(isingModel.magnetization())

print(newGrid.output(grid=isingModel.grid.grid_history[0]))
print(newGrid.output(grid=isingModel.grid.grid_history[-1]))

0.24
1.0
[[-1.  1.  1. -1. -1. -1.  1.  1.  1. -1.]
 [-1.  1.  1.  1.  1. -1. -1. -1. -1. -1.]
 [-1.  1.  1.  1. -1.  1.  1. -1. -1.  1.]
 [ 1.  1. -1. -1.  1.  1. -1.  1. -1.  1.]
 [-1.  1.  1.  1.  1. -1.  1.  1.  1.  1.]
 [ 1.  1. -1.  1. -1.  1. -1. -1.  1.  1.]
 [ 1.  1. -1.  1. -1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1. -1.  1. -1.  1. -1.  1. -1. -1.]
 [ 1.  1.  1.  1. -1.  1. -1.  1.  1. -1.]]
[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


In [5]:
holeGrid = HoleGrid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, hole_grid=np.ones((3,3)) ,c_y=2, c_x=2)
isingModel = ClassicIsing(holeGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

#isingModel.runSimulation(10)

# equilibrate the grid keeping track of grid history
print(isingModel.magnetization())
equilibrate_grid(isingModel, equil_tolerance=0.8)
print(isingModel.magnetization())

print(holeGrid.output(grid=isingModel.grid.grid_history[1]))
print(holeGrid.output(grid=isingModel.grid.grid_history[-1]))


0.11
0.81
[[-1.  1. -1.  1.  1.  1. -1. -1. -1. -1.]
 [-1.  0.  0.  0.  1.  1. -1. -1. -1.  1.]
 [-1.  0.  0.  0.  1.  1. -1. -1. -1.  1.]
 [-1.  0.  0.  0.  1.  1. -1. -1.  1.  1.]
 [-1. -1.  1.  1.  1.  1. -1. -1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1. -1.  1. -1. -1.]
 [-1.  1.  1. -1.  1.  1. -1.  1. -1. -1.]
 [-1. -1.  1.  1. -1. -1. -1.  1. -1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.  1. -1.  1.]
 [-1.  1. -1.  1.  1.  1.  1.  1. -1. -1.]]
[[ 1.  1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0. -1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [7]:
mobiusGrid = Mobius(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(mobiusGrid, temperature=1, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(isingModel, equil_tolerance=0.9)
print(isingModel.magnetization())

print(mobiusGrid.output(grid=isingModel.grid.grid_history[1]))
print(mobiusGrid.output(grid=isingModel.grid.grid_history[-1]))

0.0
0.96
[[ 1.  1.  1.  1. -1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1. -1. -1.  1.  1. -1. -1.]
 [ 1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1. -1. -1. -1. -1.  1.  1.]
 [-1.  1.  1.  1.  1. -1. -1.  1.  1.  1.]
 [ 1. -1. -1. -1.  1. -1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1.  1.  1. -1.  1.  1.  1.]
 [-1.  1.  1. -1.  1.  1. -1. -1.  1.  1.]
 [-1. -1.  1.  1.  1.  1. -1. -1. -1.  1.]
 [ 1.  1. -1.  1.  1.  1. -1. -1. -1.  1.]]
[[-1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1. -1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [8]:
cylinderGrid = Cylinder(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(cylinderGrid, temperature=1, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(isingModel, equil_tolerance=0.9)
print(isingModel.magnetization())

print(cylinderGrid.output(grid=isingModel.grid.grid_history[1]))
print(cylinderGrid.output(grid=isingModel.grid.grid_history[-1]))

0.04
0.98
[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 1.  1. -1. -1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1. -1. -1.  1. -1. -1. -1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  1.]
 [-1. -1. -1.  1.  1.  1. -1.  1.  1.  1.]
 [ 1. -1. -1.  1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1. -1. -1. -1. -1. -1.  1.]
 [ 1.  1. -1. -1. -1.  1.  1.  1. -1.  1.]]
[[-1. -1. -1. -1. -1.  1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


In [9]:
torusGrid = Torus(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron)
isingModel = ClassicIsing(torusGrid, temperature=10, ferromagnetivity=1,Mf_External=0)

#isingModel.runSimulation(10)

print(isingModel.magnetization())
equilibrate_grid(isingModel, equil_tolerance=0.9)
print(isingModel.magnetization())

print(torusGrid.output(grid=isingModel.grid.grid_history[1]))
print(torusGrid.output(grid=isingModel.grid.grid_history[-1]))

0.08
0.98
[[-1. -1. -1. -1. -1. -1.  1.  1.  1. -1.]
 [-1. -1. -1. -1. -1. -1.  1. -1. -1. -1.]
 [-1.  1. -1. -1.  1.  1.  1.  1. -1. -1.]
 [ 1.  1. -1. -1.  1.  1. -1.  1. -1.  1.]
 [-1.  1. -1. -1.  1.  1. -1. -1. -1. -1.]
 [ 1.  1. -1. -1.  1.  1. -1. -1.  1.  1.]
 [ 1.  1. -1. -1.  1.  1. -1.  1.  1.  1.]
 [-1.  1.  1.  1.  1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1. -1.  1.  1.  1.]
 [ 1.  1.  1. -1. -1. -1.  1.  1.  1.  1.]]
[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]


In [11]:
tranverseIsing = TransverseIsing(n=2, coupling_strength=1, term_strength=1, rand_init=True)


print("Initial M:", tranverseIsing.magnetization())
tranverseIsing.runSimulation(n_steps=10, dt=0.1)

print("Final M:", tranverseIsing.magnetization())

print(tranverseIsing.state_history[0])
print(tranverseIsing.state_history[-1])

Initial M: 0.15426939702359338
Final M: 0.12882619592946054
[0.38279872+0.43744677j 0.35275384+0.34579585j 0.250748  +0.41424112j
 0.25644594+0.34330836j]
[-0.07644941-0.5921258j  -0.26823755-0.30792866j -0.287291  -0.40817114j
 -0.10719938-0.46490813j]
