In [5]:
from ising_model import ClassicIsing
import electron
from grid import Grid, HoleGrid, Mobius, Cylinder, Torus
import numpy as np

# Before runnign the code, make sure to reset the kernel to clear any old imports.

In [6]:
newGrid = Grid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, random_seed=12)
isingModel = ClassicIsing(newGrid, temperature=1, ferromagnetivity=.1,Mf_External=0,)

isingModel.runSimulation(10)

print(Grid.output(grid=isingModel.grid.grid_history[0]))
print(Grid.output(grid=isingModel.grid.grid_history[-1]))

[[ 1.  1. -1.  1.  1. -1.  1.  1. -1. -1.]
 [-1.  1. -1.  1.  1.  1. -1.  1. -1. -1.]
 [-1.  1. -1. -1.  1. -1.  1.  1. -1. -1.]
 [ 1.  1. -1.  1.  1. -1. -1. -1. -1. -1.]
 [-1. -1.  1.  1.  1.  1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1. -1.  1.  1. -1.  1. -1.]
 [-1. -1. -1.  1.  1. -1.  1.  1.  1.  1.]
 [-1.  1.  1.  1.  1.  1. -1. -1. -1. -1.]
 [-1.  1.  1. -1. -1. -1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1.  1.  1. -1.  1.  1.]]
[[-1. -1.  1.  1.  1. -1. -1.  1. -1.  1.]
 [ 1.  1. -1. -1.  1. -1. -1. -1. -1. -1.]
 [-1. -1.  1. -1. -1. -1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1. -1.  1. -1. -1. -1.  1.]
 [-1.  1.  1. -1. -1.  1. -1. -1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1.  1.  1.  1. -1.]
 [ 1. -1.  1.  1.  1.  1. -1.  1. -1.  1.]
 [-1. -1.  1.  1. -1. -1.  1. -1.  1. -1.]
 [ 1.  1.  1.  1.  1. -1. -1. -1.  1. -1.]
 [-1. -1. -1. -1. -1.  1. -1. -1. -1. -1.]]


In [7]:
np.array_equal(Grid.output(grid=isingModel.grid.grid_history[1]), (Grid.output(grid=isingModel.grid.grid_history[-1])))

False

In [8]:
holeGrid = HoleGrid(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, random_seed=2, hole_grid=np.ones((3,3)) ,c_y=2, c_x=2)
isingModel = ClassicIsing(holeGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

isingModel.runSimulation(10)
print(HoleGrid.output(grid=isingModel.grid.grid_history[1]))
print(HoleGrid.output(grid=isingModel.grid.grid_history[-1]))

[[ 1.  1. -1. -1.  1.  1.  1. -1.  1. -1.]
 [ 1.  0.  0.  0.  1.  1.  1. -1.  1.  1.]
 [ 1.  0.  0.  0. -1. -1.  1.  1.  1.  1.]
 [-1.  0.  0.  0. -1.  1.  1.  1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1. -1.  1.  1.  1.]
 [ 1. -1. -1. -1.  1.  1.  1.  1.  1. -1.]
 [-1. -1. -1. -1.  1.  1.  1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.  1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [-1.  0.  0.  0.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1. -1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1. -1.  1. -1.  1.  1.]]


In [9]:
holeGrid = Mobius(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, random_seed=2)
isingModel = ClassicIsing(holeGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

isingModel.runSimulation(10)

print(Mobius.output(grid=isingModel.grid.grid_history[1]))
print(Mobius.output(grid=isingModel.grid.grid_history[-1]))

[[-1.  1.  1. -1. -1.  1. -1.  1. -1.  1.]
 [-1.  1.  1.  1.  1.  1.  1.  1. -1. -1.]
 [-1. -1.  1.  1.  1. -1. -1. -1.  1.  1.]
 [ 1. -1. -1.  1. -1. -1.  1.  1.  1. -1.]
 [-1. -1. -1.  1.  1.  1.  1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1. -1.  1.  1.  1. -1.  1.]
 [ 1. -1. -1. -1.  1.  1.  1.  1. -1. -1.]
 [-1. -1.  1. -1.  1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  1. -1.  1. -1. -1.]]
[[-1.  1.  1. -1. -1.  1. -1.  1. -1.  1.]
 [-1.  1.  1.  1.  1.  1.  1.  1. -1. -1.]
 [-1. -1.  1.  1.  1. -1. -1. -1.  1.  1.]
 [ 1. -1. -1.  1. -1. -1.  1.  1.  1. -1.]
 [-1. -1. -1.  1.  1.  1.  1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1. -1.  1.  1.  1. -1.  1.]
 [ 1. -1. -1. -1.  1.  1.  1.  1. -1. -1.]
 [-1. -1.  1. -1.  1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  1. -1.  1. -1. -1.]]


In [10]:
holeGrid = Cylinder(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, random_seed=2)
isingModel = ClassicIsing(holeGrid, temperature=1, ferromagnetivity=1,Mf_External=0,)

isingModel.runSimulation(10)

print(Cylinder.output(grid=isingModel.grid.grid_history[1]))
print(Cylinder.output(grid=isingModel.grid.grid_history[-1]))

[[ 1.  1. -1. -1.  1.  1.  1.  1.  1. -1.]
 [ 1. -1. -1. -1.  1.  1.  1. -1.  1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.  1.  1. -1. -1. -1.]
 [-1. -1.  1. -1. -1.  1.  1.  1.  1.  1.]
 [-1. -1. -1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]
 [-1. -1. -1. -1.  1.  1.  1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  1.  1.  1. -1. -1.]
 [-1. -1. -1. -1.  1.  1.  1.  1.  1.  1.]]
[[-1. -1. -1. -1. -1.  1. -1.  1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 1.  1. -1. -1. -1. -1. -1. -1.  1.  1.]
 [ 1.  1.  1.  1. -1. -1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [11]:
holeGrid = Torus(n_x=10, n_y=10, gridPointObject=electron.ClassicElectron, random_seed=2)
isingModel = ClassicIsing(holeGrid, temperature=10, ferromagnetivity=1,Mf_External=0,)

isingModel.runSimulation(10)

print(Torus.output(grid=isingModel.grid.grid_history[1]))
print(Torus.output(grid=isingModel.grid.grid_history[-1]))

[[ 1. -1. -1.  1.  1.  1.  1. -1.  1. -1.]
 [ 1. -1. -1.  1.  1.  1. -1. -1.  1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1.  1. -1. -1.]
 [-1.  1.  1. -1.  1.  1. -1. -1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1. -1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. -1. -1. -1. -1. -1.]
 [ 1.  1.  1. -1.  1. -1. -1. -1. -1. -1.]
 [-1.  1.  1.  1.  1. -1. -1. -1.  1.  1.]
 [-1.  1. -1.  1. -1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. -1.  1. -1.  1.  1.]]
[[-1. -1. -1.  1. -1. -1. -1. -1. -1. -1.]
 [ 1. -1. -1. -1. -1.  1. -1.  1. -1.  1.]
 [-1. -1. -1. -1.  1.  1.  1.  1. -1. -1.]
 [-1. -1.  1. -1.  1.  1.  1. -1.  1.  1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1. -1.  1.]
 [-1. -1. -1. -1. -1. -1.  1.  1. -1. -1.]
 [ 1.  1.  1. -1. -1. -1.  1.  1.  1.  1.]
 [ 1. -1. -1.  1.  1.  1. -1.  1.  1. -1.]
 [ 1. -1. -1. -1.  1.  1.  1.  1. -1.  1.]
 [ 1. -1. -1.  1.  1. -1. -1.  1. -1. -1.]]
